# Generated by Django 3.2.8 on 2021-10-08 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('created_by', models.CharField(max_length=200)),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_andsighting', to='users.sightingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likesusername', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
