# Generated by Django 3.2.8 on 2021-10-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211008_2239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sightinglikes',
            unique_together={('sight', 'created_by')},
        ),
    ]
