# Generated by Django 3.2.8 on 2021-10-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_sightinglikes_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
